insert into cidade(nome, uf)values
('Adamantina','SP'),
('Adolfo','SP'),
('Aguaí','SP'),
('Águas da Prata','SP'),
('Águas de Lindóia','SP'),
('Águas de Santa Bárbara','SP'),
('Águas de São Pedro','SP'),
('Agudos','SP'),
('Alambari','SP'),
('Alfredo Marcondes','SP'),
('Altair','SP'),
('Altinópolis','SP'),
('Alto Alegre','SP'),
('Alumínio','SP'),
('Álvares Machado','SP'),
('Álvares Florence','SP'),
('Álvaro de Carvalho','SP'),
('Alvinlândia','SP'),
('Americana','SP'),
('Américo Brasiliense','SP'),
('Américo de Campos','SP'),
('Amparo','SP'),
('Analândia','SP'),
('Andradina','SP'),
('Angatuba','SP'),
('Anhembi','SP'),
('Anhumas','SP'),
('Aparecida','SP'),
('Aparecida d Oeste','SP'),
('Apiaí','SP'),
('Araçariguama','SP'),
('Araçatuba','SP'),
('Araçoiaba da Serra','SP'),
('Aramina','SP'),
('Arandu','SP'),
('Arapeí','SP'),
('Araraquara','SP'),
('Araras','SP'),
('Arco-íris','SP'),
('Arealva','SP'),
('Areias','SP'),
('Areiópolis','SP'),
('Ariranha','SP'),
('Artur Nogueira','SP'),
('Arujá','SP'),
('Aspásia','SP'),
('Assis','SP'),
('Atibaia','SP'),
('Auriflama','SP'),
('Avaí','SP'),
('Avanhandava','SP'),
('Avaré','SP'),
('Bady Bassitt','SP'),
('Balbinos','SP'),
('Bálsamo','SP'),
('Bananal','SP'),
('Barão de Antonina','SP'),
('Barbosa','SP'),
('Bariri','SP'),
('Barra Bonita','SP'),
('Barra do Chapéu','SP'),
('Barra do Turvo','SP'),
('Barretos','SP'),
('Barrinha','SP'),
('Barueri','SP'),
('Bastos','SP'),
('Batatais','SP'),
('Bauru','SP'),
('Bebedouro','SP'),
('Bento de Abreu','SP'),
('Bernardino de Campos','SP'),
('Bertioga','SP'),
('Bilac','SP'),
('Birigui','SP'),
('Biritiba Mirim','SP'),
('Boa Esperança do Sul','SP'),
('Bocaina','SP'),
('Bofete','SP'),
('Boituva','SP'),
('Bom Jesus dos Perdões','SP'),
('Bom Sucesso de Itararé','SP'),
('Borá','SP'),
('Boraceia','SP'),
('Borborema','SP'),
('Borebi','SP'),
('Botucatu','SP'),
('Bragança Paulista','SP'),
('Braúna','SP'),
('Brejo Alegre','SP'),
('Brodowski','SP'),
('Brotas','SP'),
('Buri','SP'),
('Buritama','SP'),
('Buritizal','SP');
